# Generated by Django 3.1.2 on 2020-10-20 16:35

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, size=3)),
            ],
        ),
    ]
